version: '3.8'

services:
  soundance-streamer-python:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/soundance-streamer-python
    command: python main.py
    restart: unless-stopped
